#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Copyright (c) 2020, MrDoob
# All rights reserved.

# shellcheck disable=SC2086
umask 022
#command="python3 /app/tautulli/Tautulli.py"
command_2="chown tautulli:tautulli /app/tautulli"
$command_2
echo "-> Starting Tautulli <-"
#exec s6-setuidgid tautulli $command --datadir /config
exec \
	s6-setuidgid abc python3 /app/tautulli/Tautulli.py \
	--datadir /config
